-- Auto-generated by ii wallpaper theming system
-- Do not edit manually - changes will be overwritten

return {
  foreground = '#A4A49E',
  background = '#181616',
  
  cursor_bg = '#A4A49E',
  cursor_fg = '#181616',
  cursor_border = '#A4A49E',
  
  selection_fg = '#181616',
  selection_bg = '#A4A49E',
  
  scrollbar_thumb = '#737C73',
  split = '#737C73',
  
  ansi = {
    '#181616',  -- black
    '#BC6490',  -- red
    '#64BC82',  -- green
    '#BBC859',  -- yellow
    '#6494BC',  -- blue
    '#AE64BC',  -- magenta
    '#64BCB8',  -- cyan
    '#A4A49E',  -- white
  },
  
  brights = {
    '#737C73',  -- bright black
    '#D083AA',  -- bright red
    '#83D09D', -- bright green
    '#CED97B', -- bright yellow
    '#83ADD0', -- bright blue
    '#C383D0', -- bright magenta
    '#83D0CC', -- bright cyan
    '#C5C9C5', -- bright white
  },
  
  tab_bar = {
    background = '#181616',
    active_tab = {
      bg_color = '#92a1a9',
      fg_color = '#181616',
    },
    inactive_tab = {
      bg_color = '#737C73',
      fg_color = '#A4A49E',
    },
    inactive_tab_hover = {
      bg_color = '#737C73',
      fg_color = '#C5C9C5',
    },
  },
}
